services:
  fastapi_app:
    build: .
    container_name: ecommerce
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - "/Users/diegogaibor/Documents/Kruger/proyecto4gen/backend:/app"
    environment:
      MongoDB_URI: 
      JWT_SECRET_KEY: secret123
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
